#!/bin/bash
#
# Script that will:
#
#		1.  Shut down Docker CI System.
#		2.  Remove Existing Docker-Containers (Leaves Data-Volumes As-Is Default).
#   3.  Remove Dangling Docker-Containers
#
#   4.  Re-Starts Docker Containers
#
#	 set -x

usage(){
		echo " "
		echo " "
		echo " "
		echo "Usage: $0 "
		echo " "
		echo " "
		echo "   Completes docker-compose down then up on CI System."
		echo " "
		exit 1
}
  
	i=0
	for argz in "$@"
	do
	    #echo "Here be Arg.$i: $argz"

	 		if [ $i -gt 0 ]
	   		then
					case "$argz" in

					    -H)
									usage
									exit 3
					        ;;

					    -h)
									usage
									exit 3
									;;

					    --H)
									usage
									exit 3
					        ;;

					    --h)
									usage
									exit 3
									;;

					    -help)
									usage
									exit 3
					        ;;

					    --help)
									usage
									exit 3
									;;


					    *)
					    		#echo "Invalid Option: $var"
					    		#usage
					    		#exit 77
					        ;;
					esac

			fi

			((i=i+1))

	done
	   
	tLogFile=
	tLogFile="/data/txt/cycleCISystemLog.txt"
	
	tCMD=
	
	rm "$tLogFile"
	
	cd /dev2/docker/eric/master/docker-ci-toolz-stack-master/azure/tools
	
	echo " "
	echo "Shutting Down CI System...."
	echo " "
		   
	tCMD="docker-compose -f ./docker-compose-v3.yaml down " 
	
	$tCMD | tee -a $tLogFile
	
	echo " "
	echo "Remove Any Existing Containers...."
	echo " "
	
	/dev2/sh/killDockerDanglerz | tee -a "$tLogFile"
	
	echo " "
	echo "Remove Any Exited Containers...."
	echo " "
	
	/dev2/sh/killDockerContainersExited | tee -a "$tLogFile"
	
	echo " "
	echo "Re-Starting CI System...."
	echo " "
	
	tCMD="docker-compose -f ./docker-compose-v3.yaml up "
	
	$tCMD | tee -a $tLogFile
	
	exit 0
	
	
