---
version: "3"
services:
  nexus:
    image: harbor04.azure.csp-si-tiger.net/ericm48/dockercitoolstackmaster_nexus:3.69.0-java11
    container_name: nexus-3.69.0-java11
    ports:
      - "8081:8081"
    volumes:
      - /mnt/dockervolumes/data/nexus-data:/nexus-data 
