---
version: "3"
services:
  jenkins:
    image: harbor04.azure.csp-si-tiger.net/ericm48/dockercitoolstackmaster_jenkins:1.642.2
    container_name: jenkins-1.642.2
    ports:
      - "8080:8080"
    volumes:
      - /mnt/dockervolumes/data/jenkins:/var/jenkins_home
      
    environment:
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}

