---
version: "3"
services:
  nginx:
    image: harbor04.azure.csp-si-tiger.net/ericm48/dockercitoolstackmaster_nginx:1.19.3
    container_name: nginx-1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf

    network_mode: host

  jenkins:
    image: harbor04.azure.csp-si-tiger.net/ericm48/dockercitoolstackmaster_jenkins:1.642.2
    container_name: jenkins-1.642.2
    ports:
      - "8080:8080"
    volumes:
      - /mnt/dockervolumes/data/jenkins:/var/jenkins_home

    environment:
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}

  nexus:
    image: harbor04.azure.csp-si-tiger.net/ericm48/nexus:3.67.1-01-j8
    container_name: nexus-3.67.1-01-j8

    ports:
      - "8081:8081"
    volumes:
      - /mnt/dockervolumes/data/nexus-data:/nexus-data 
