---
version: "3"
services:
  nginx:
    image: harbor04.azure.csp-si-tiger.net/ericm48/dockercitoolstackmaster_nginx:1.19.3
    container_name: nginx-1.19.3
    ports:
      - 80:80
      - 443:443
    volumes:
      # NginX:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/ssl/nginx/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./nginx/etc/ssl/nginx/privkey.pem:/etc/nginx/ssl/privkey.pem
      - ./nginx/etc/ssl/nginx/nginx.azure.csp-si-tiger.net-root.crt:/etc/nginx/ssl/nginx.azure.csp-si-tiger.net-root.crt
      - /mnt/dockervolumes/var/log:/var/log

      # Nexus:
      - ./nginx/etc/ssl/nexus/fullchain.pem:/etc/nexus/ssl/fullchain.pem
      - ./nginx/etc/ssl/nexus/privkey.pem:/etc/nexus/ssl/privkey.pem
      
      # Jenkins:
      - ./nginx/etc/ssl/jenkins/fullchain.pem:/etc/jenkins/ssl/fullchain.pem
      - ./nginx/etc/ssl/jenkins/privkey.pem:/etc/jenkins/ssl/privkey.pem

    network_mode: host

  jenkins:
    image: harbor04.azure.csp-si-tiger.net/ericm48/dockercitoolstackmaster_jenkins:1.642.2
    container_name: jenkins-1.642.2
    ports:
      - "8080:8080"
    volumes:
      - /mnt/dockervolumes/data/jenkins:/var/jenkins_home

    environment:
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}

  nexus:
    image: harbor04.azure.csp-si-tiger.net/ericm48/dockercitoolstackmaster_nexus:3.69.0-java11           
    container_name: nexus-3.69.0-java11

    ports:
      - "8081:8081"
    volumes:
      - /mnt/dockervolumes/data/nexus-data:/nexus-data 
