---

sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar

db:
  image: sameersbn/postgresql:9.4-3 #postgres
  net: container:sonar
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

postgresql:
  image: sameersbn/postgresql:9.4-3
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /mnt/dockervolumes/data/postgresql:/var/lib/postgresql

