---
version: "3"

services:
  sonarqube:
    image: sonarqube:lts-community # sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:  
     - /mnt/dockervolumes/data/sonarqube/conf:/opt/sonarqube/conf
     - /mnt/dockervolumes/data/sonarqube/data:/opt/sonarqube/data
     - /mnt/dockervolumes/data/sonarqube/extensions:/opt/sonarqube/extensions
     - /mnt/dockervolumes/data/sonarqube/temp:/opt/sonarqube/temp
     - /mnt/dockervolumes/var/log/sonarqube:/opt/sonarqube/logs 

  sonar_db:
    image: postgres:13.16-bullseye #postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - /mnt/dockervolumes/data/postgresql:/var/lib/postgresql
      - /mnt/dockervolumes/data/postgresql/data:/var/lib/postgresql/data
      