---
version: "3"
services:
  nginx:
    image: ericm24/dockercitoolstackmaster_nginx:1.19.3
    container_name: nginx-1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host

  jenkins:
    image: ericm24/dockercitoolstackmaster_jenkins:1.642.2
    container_name: jenkins-1.642.2
    ports:
      - "8080:8080"
#
# Remember!!! Environment only applies to runtime, NOT BUILDTIME for docker, so no --build-args (until docker-compose version 1.9.0.x)
#
    environment:
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}

    volumes:
      - /mnt/dockervolumes/data/jenkins:/var/jenkins_home

  nexus:
    image: ericm24/dockercitoolstackmaster_nexus:3.67.1-01-j8
    container_name: nexus-3.67.1-01-j8
    ports:
      - "8081:8081"

    volumes:
      - /mnt/dockervolumes/data/nexus:/sonatype-work

